### ISSUE TITLE
Option to disable slider to select numerical values

### ISSUE THREAD

**Issue by chilbes** [uzh-bf/klicker-uzh-legacy#136]
In most of the cases, the slider to select an answer in numerical question is more distracting than helping.

- On a mobile device, the slider is very dominant: users do not realize there is a text entry field and believe entry is limited to what the slider can do

- The slider moves in integral steps which is in most of at least my cases not useful (typically real number as results)

Could we get an option to disable the slider presence?

**Comment by rschlaefli** [comment]
The slider has been removed entirely, as we do not feel it was that useful anyways.
