### ISSUE TITLE
Sometimes unable to enter whitespace character while editing a question

### ISSUE THREAD

**Issue by ethaden** [uzh-bf/klicker-uzh-legacy#258]
**Describe the bug**
In the current live system at https://app.klicker.uzh.ch (don't know how to check the version), it is often not possible to enter a whitespace character into the text fields. Sometimes removing the content and pressing "space" solves that issue but not always.

**To Reproduce**
1. Create a new question.
2. Add some text to the question title or the question text.

**Expected behavior**
It should be possible to enter whitespace.

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu Linux
 - Browser Firefox 79.0

**Comment by rschlaefli** [comment]
Hi @ethaden,

We have fixed this issue and will release a new version today. Thanks for your interest in our open source project.

Best regards,
Roland Schläfli
