### ISSUE TITLE
Feedbacks disappear after submitting new feedback

### ISSUE THREAD

**Issue by sraimund** [uzh-bf/klicker-uzh-legacy#282]
After submitting a "New open feedback" in the Student View, previous list items in "All feedbacks" disappear. You have to reload the page to make the given feedbacks appear again.

Steps to reproduce:
- start a new session
- activate Feedback-Channel and Publish feedbacks
- go to Student View
- submit a feedback
- the answer is added but immediately afterwards all feedbacks disappear

Expected behaviour:
The submitted answer is added to the other feedbacks.

Tested version:
https://app.klicker.uzh.ch

**Comment by rschlaefli** [comment]
Hi @sraimund 

Thanks a lot for your bug report and your interest in the KlickerUZH.
We have fixed the issue and are pushing out a new release tonight.


Best,
Roland

**Comment by sraimund** [comment]
Thank you, Roland. I tested it just now and it works.
